<?php

namespace app\controllers;

use app\api\DreamAnalysis\AddWordRequest;
use app\api\DreamAnalysis\DreamAnalysisApi;
use app\components\gui\ActionItem;
use app\components\gui\Breadcrumb;
use app\components\gui\flash\Flash;
use app\components\gui\js\Script;
use app\models\dj\WordToCategory;
use app\models\freud\Word;
use Yii;
use app\models\dj\DreamCategory;
use app\models\dj\DreamCategorySearch;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * DreamcategoryController implements the CRUD actions for DreamCategory model.
 */
class DreamcategoryController extends BaseController
{
	/**
	 * {@inheritdoc}
	 */
	public function behaviors()
	{
		$access = $this->getDefaultAccess();
		return $access;
	}

    public function beforeAction($action)
	{
		$this->addBreadcrumb(new Breadcrumb('Dream Categories', '/dreamcategory'));
		$this->addActionItem(new ActionItem('New', '/dreamcategory/new', 'primary'));

		//Register Vue for dream comments
		$this->getScriptRegistrar()->registerScript(
			new Script('vue/vue.js')
		);

		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}

	/**
     * Lists all DreamCategory models.
     * @return mixed
     */
    public function actionIndex()
    {
		$this->getView()->title = 'Dream Categories';

        $searchModel = new DreamCategorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $request = Yii::$app->request;

        $type = $request->getQueryParam('type');
		if($type == 'json')
		{
			return $this->asJson(DreamCategory::find()->all());
		}
        else
		{
			return $this->render('index', [
				'searchModel' => $searchModel,
				'dataProvider' => $dataProvider,
			]);
		}
    }

    /**
     * Displays a single DreamCategory model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
		$this->getScriptRegistrar()->registerScript(new Script('dream/category.js'));

		$this->addBreadcrumb(new Breadcrumb('View', '', true));

		$this->addActionItem(new ActionItem('Edit', '/dreamcategory/edit/' . $id, 'secondary'));
		$this->addActionItem(new ActionItem('Delete', '/dreamcategory/delete/' . $id, 'danger'));

    	$this->getView()->title = 'View Dream Category';

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new DreamCategory model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionNew()
    {
		$this->getScriptRegistrar()->registerScript(new Script('dream/category.js'));

		$this->addBreadcrumb(new Breadcrumb('New', '', true));

    	$this->getView()->title = 'New Dream Category';

        $model = new DreamCategory();

        if($this->getRequest()->getIsPost())
		{
			$post = $this->getRequest()->post();
			$model->load($post);

			if($model->save())
			{
				$categoryWords = $post['Category']['word'] ?? [];
				//Add words to category
				if($categoryWords)
				{
					foreach($categoryWords as $wordInfo)
					{
						$categoryWord = trim($wordInfo['word'] ?? '');
						$certainty = floatval($wordInfo['certainty'] ?? NULL);
						if(!$certainty)
						{
							$certainty = 1;
						}

						$word = Word::find()->word($categoryWord)->one();
						if(!$word)
						{
							//Create the word!
							$categoryWord = str_replace(' (new)', '', $categoryWord);
							$dreamAnalysis = new DreamAnalysisApi();
							$wordRequest = new AddWordRequest();
							$wordRequest->word = $categoryWord;
							$wordResponse = $dreamAnalysis->addWord($wordRequest);
							if($wordResponse->isSuccess())
							{
								$word = Word::find()->word($wordResponse->word)->one();
							}
							else
							{
								$this->addFlash(new Flash('Failed to add word ' . $categoryWord . ': ' . $wordResponse->error .  '.', Flash::WARNING));
							}
						}

						if($word)
						{
							$model->link('words', $word, [
								'certainty' => $certainty
							]);
						}
					}
				}
				$this->addFlash(new Flash('Successfully saved category.', Flash::SUCCESS));
			}
			else
			{
				$this->addFlash(new Flash('Failed to save category.', Flash::FAILURE));
			}

			return $this->redirect(['view', 'id' => $model->id]);
		}

        return $this->render('_form', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing DreamCategory model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionEdit($id)
    {
		$this->getScriptRegistrar()->registerScript(new Script('dream/category.js'));

		$this->addBreadcrumb(new Breadcrumb('Edit', '', true));
		$this->addActionItem(new ActionItem('Cancel', '/dreamcategory/view/' . $id, 'secondary'));

    	$this->getView()->title = 'Edit Dream Category';

        $model = $this->findModel($id);

        if($this->getRequest()->getIsPost())
		{
			$post = $this->getRequest()->post();
			$model->load($post);

			if($model->save())
			{
				$model->unlinkAll('words', true);

				$categoryWords = $post['Category']['word'] ?? [];
				//Add words to category
				if($categoryWords)
				{
					foreach($categoryWords as $wordInfo)
					{
						$categoryWord = trim($wordInfo['word'] ?? '');
						$certainty = floatval($wordInfo['certainty'] ?? NULL);
						if(!$certainty)
						{
							$certainty = 1;
						}

						$word = Word::find()->word($categoryWord)->one();
						if(!$word)
						{
							//Create the word!
							$categoryWord = str_replace(' (new)', '', $categoryWord);
							$dreamAnalysis = new DreamAnalysisApi();
							$wordRequest = new AddWordRequest();
							$wordRequest->word = $categoryWord;
							$wordResponse = $dreamAnalysis->addWord($wordRequest);
							if($wordResponse->isSuccess())
							{
								$word = Word::find()->word($wordResponse->word)->one();
							}
							else
							{
								$this->addFlash(new Flash('Failed to add word ' . $categoryWord . ': ' . $wordResponse->error .  '.', Flash::WARNING));
							}
						}

						if($word)
						{
							$model->link('words', $word, [
								'certainty' => $certainty
							]);
						}
					}
				}
				$this->addFlash(new Flash('Successfully saved category.', Flash::SUCCESS));
			}
			else
			{
				$this->addFlash(new Flash('Failed to save category.', Flash::FAILURE));
			}
		}

        return $this->render('_form', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing DreamCategory model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

	# AJAX Routes

	/**
	 * Gets all of the words for a concept.
	 *
	 * @param int $id
	 */
	public function actionCategorywords(int $id)
	{
		$category = $this->findModel($id);
		$words = $category->words;

		$wordData = [];
		foreach($words as $word)
		{
			$wordWithCertainty = [];
			$wordWithCertainty['id'] = $word->id;
			$wordWithCertainty['word'] = $word->word;

			$wordToCategory = WordToCategory::find()->andWhere(['word_id' => $word->id])->andWhere(['category_id' => $id])->one();
			if($wordToCategory)
			{
				$wordWithCertainty['certainty'] = $wordToCategory->certainty;
			}
			$wordData[] = $wordWithCertainty;
		}

		return $this->asJson($wordData);
	}

	/**
	 * Gets all of the words as AJAX based on the search string.
	 *
	 * @param string $search
	 */
	public function actionWords(string $search)
	{
		//Search for matches
		$words = Word::find()->wordLike($search)->all();

		//Add unknown word to results so that it can be selected and created
		if(!Word::find()->word($search)->exists())
		{
			$word = new Word();
			$word->word = $search . ' (new)';
			$word->id = $word->word;
			array_unshift($words, $word);
		}

		$wordData = [];
		foreach($words as $word)
		{
			$wordData[] = [
				'id' => $word->word,
				'text' => $word->word
			];
		}
		return $this->asJson(['results' => $wordData]);
	}

    /**
     * Finds the DreamCategory model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return DreamCategory the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = DreamCategory::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}
